const GENERATED_HEADER =
  '// This file is generated by `pnpm i18n:generate`. Do not edit it manually.\n';

export function renderNvapiContract(sourceMessages, verbatimValues, settingCount) {
  const verbatimTranslations = Object.fromEntries(verbatimValues.map((value) => [value, value]));
  return `${GENERATED_HEADER}
export const NVAPI_SOURCE_CATALOG = ${JSON.stringify(sourceMessages, null, 2)} as const;
export const NVAPI_VERBATIM_TRANSLATIONS = ${JSON.stringify(verbatimTranslations, null, 2)} as const;
export const NVAPI_SETTING_COUNT = ${JSON.stringify(settingCount)} as const;

export type NvapiSourceCatalog = typeof NVAPI_SOURCE_CATALOG;
export type NvapiMessageKey = keyof NvapiSourceCatalog;
export type NvapiSourceText = NvapiSourceCatalog[NvapiMessageKey];
export type NvapiVerbatimSourceText = keyof typeof NVAPI_VERBATIM_TRANSLATIONS;
export type NvapiLocalizedSourceText = Exclude<NvapiSourceText, NvapiVerbatimSourceText>;
export type NvapiTranslations = Readonly<Record<NvapiLocalizedSourceText, string>>;
export type ExpandedNvapiCatalog<Translations extends NvapiTranslations> = Readonly<{
  [Key in NvapiMessageKey]: NvapiSourceCatalog[Key] extends NvapiVerbatimSourceText
    ? NvapiSourceCatalog[Key]
    : Translations[Extract<NvapiSourceCatalog[Key], NvapiLocalizedSourceText>];
}>;

export function expandNvapiTranslations<const Translations extends NvapiTranslations>(
  localized: Translations,
): ExpandedNvapiCatalog<Translations> {
  return Object.fromEntries(
    Object.entries(NVAPI_SOURCE_CATALOG).map(([key, source]) => [
      key,
      Object.hasOwn(NVAPI_VERBATIM_TRANSLATIONS, source)
        ? source
        : localized[source as NvapiLocalizedSourceText],
    ]),
  ) as ExpandedNvapiCatalog<Translations>;
}
`;
}

export function renderLumaContract({ sourceCatalog, contexts }) {
  return `${GENERATED_HEADER}
export const LUMA_SOURCE_CATALOG = ${JSON.stringify(sourceCatalog, null, 2)} as const;
export const LUMA_MESSAGE_CONTEXTS = ${JSON.stringify(contexts, null, 2)} as const;

export type LumaSourceCatalog = typeof LUMA_SOURCE_CATALOG;
export type LumaMessageKey = keyof LumaSourceCatalog;
export type LumaMessageContext = (typeof LUMA_MESSAGE_CONTEXTS)[LumaMessageKey];
export type LumaTranslations = Readonly<Record<LumaMessageKey, string>>;
`;
}

export function renderOptiscalerContract({ sourceCatalog, contexts }) {
  return `${GENERATED_HEADER}
export const OPTISCALER_SOURCE_CATALOG = ${JSON.stringify(sourceCatalog, null, 2)} as const;
export const OPTISCALER_MESSAGE_CONTEXTS = ${JSON.stringify(contexts, null, 2)} as const;

export type OptiScalerSourceCatalog = typeof OPTISCALER_SOURCE_CATALOG;
export type OptiScalerMessageKey = keyof OptiScalerSourceCatalog;
export type OptiScalerMessageContext = (typeof OPTISCALER_MESSAGE_CONTEXTS)[OptiScalerMessageKey];
export type OptiScalerTranslations = Readonly<Record<OptiScalerMessageKey, string>>;
`;
}

export function renderRenodxContract({ sourceCatalog, contexts }) {
  return `${GENERATED_HEADER}
export const RENODX_SOURCE_CATALOG = ${JSON.stringify(sourceCatalog, null, 2)} as const;
export const RENODX_MESSAGE_CONTEXTS = ${JSON.stringify(contexts, null, 2)} as const;

export type RenoDxSourceCatalog = typeof RENODX_SOURCE_CATALOG;
export type RenoDxMessageKey = keyof RenoDxSourceCatalog;
export type RenoDxMessageContext = (typeof RENODX_MESSAGE_CONTEXTS)[RenoDxMessageKey];
export type RenoDxTranslations = Readonly<Record<RenoDxMessageKey, string>>;
`;
}

export function renderContractVersion(version) {
  return `${GENERATED_HEADER}
export const MESSAGE_CONTRACT_VERSION = ${JSON.stringify(version)} as const;
`;
}

export function renderDesktopCommandErrorContract(contract) {
  const frontendContract = {
    schemaVersion: contract.schemaVersion,
    commandErrors: Object.fromEntries(
      Object.entries(contract.commandErrors).map(([code, spec]) => [
        code,
        {
          messageKey: spec.messageKey,
          severity: spec.severity,
          actions: spec.actions,
          reasonCodes: spec.reasonCodes,
          recoveryBundlePath: spec.recoveryBundlePath,
        },
      ]),
    ),
    suggestedActions: contract.suggestedActions,
  };

  return `${GENERATED_HEADER}
export const DESKTOP_COMMAND_ERROR_CONTRACT = ${JSON.stringify(frontendContract, null, 2)} as const;

export const COMMAND_ERROR_CONTRACT = DESKTOP_COMMAND_ERROR_CONTRACT.commandErrors;
export const SUGGESTED_ACTION_CONTRACT = DESKTOP_COMMAND_ERROR_CONTRACT.suggestedActions;

export type CommandErrorCode = keyof typeof COMMAND_ERROR_CONTRACT;
export type SuggestedActionCode = keyof typeof SUGGESTED_ACTION_CONTRACT;
`;
}

export function renderAddGameWarningContract(contract) {
  return `${GENERATED_HEADER}
export const ADD_GAME_WARNING_CONTRACT = ${JSON.stringify(contract.addGameWarnings, null, 2)} as const;

export type AddGameWarningCode = keyof typeof ADD_GAME_WARNING_CONTRACT;
`;
}
