// This file is generated by `pnpm i18n:generate`. Do not edit it manually.

export const RENODX_SOURCE_CATALOG = {
  'renodx.black_myth_wukong.hdr': 'In Engine.ini, add this setting for the UE Extended HDR path.',
  'renodx.external.discord': 'Get the add-on from Discord, then install the downloaded file.',
  'renodx.external.nexus': 'Get the add-on from Nexus Mods, then install the downloaded file.',
  'renodx.generic.ue_extended': 'Uses the shared Unreal Engine Extended profile.',
  'renodx.generic.unity': 'Uses the shared Unity engine profile.',
  'renodx.generic.unreal_legacy': 'Uses a title-specific legacy Unreal Engine profile.',
  'renodx.main.assassin.s.creed.iv.black.flagtm.1':
    'The mod is playable, but some graphics issues remain unresolved.',
  'renodx.main.atelier.yumia.the.alchemist.of.memories.the.envisioned.land.1':
    'The mod is considered playable but still needs broader playtesting.',
  'renodx.main.atlas.fallen.dx12.1': "Install ReShade in the game's Atlas Fallen\\bin directory.",
  'renodx.main.atlas.fallen.dx12.2': 'FSR 2 can cause crashes with this mod.',
  'renodx.main.clive.barker.s.jericho.1': 'ACES output is currently broken in this build.',
  'renodx.main.crimson.desert.1':
    'Frequent game updates can break the mod; re-check compatibility after each update.',
  'renodx.main.days.gone.1':
    'This dedicated build is functional, but its HDR result may still need refinement.',
  'renodx.main.dead.island.riptide.definitive.edition.1':
    'The current dedicated mod build is broken.',
  'renodx.main.dragon.s.dogma.2.1':
    'After installing the mod, delete shader.cache2 from the game directory to avoid shader stutter.',
  'renodx.main.forza.horizon.6.1':
    "The game's native HDR already works well; this mod offers an alternative presentation rather than an HDR fix.",
  'renodx.main.ninja.gaiden.4.1': "This mod requires Lyall's NinjaGaidenMCFix.",
  'renodx.main.ninja.gaiden.sigma.1': "This mod requires Lyall's NinjaGaidenMCFix.",
  'renodx.main.ninja.gaiden.sigma.2.1': "This mod requires Lyall's NinjaGaidenMCFix.",
  'renodx.main.opus.echo.of.starsong.full.bloom.edition.1':
    'Disable the Steam overlay. If problems remain, disable other overlays as well.',
  'renodx.main.raidou.remastered.the.mystery.of.the.soulless.army.1':
    'The mod needs more playtesting; shaders may be missing in later areas.',
  'renodx.main.s.t.a.l.k.e.r.2.heart.of.chornobyl.1': 'Apply these in-game display settings.',
  'renodx.main.sonic.unleashed.recompiled.1': 'Disable motion blur before using this mod.',
  'renodx.main.sonic.unleashed.recompiled.2':
    'The current mod build does not work on GeForce RTX 50-series GPUs.',
  'renodx.main.steelrising.1': 'The current dedicated mod build is broken.',
  'renodx.main.the.evil.within.2.1':
    'The mod is considered playable but still needs broader playtesting.',
  'renodx.main.trackmania.1': 'HDR works well, but some customization menus are broken.',
  'renodx.main.yakuza.kiwami.1.1':
    'This build was primarily designed for Yakuza 0; Yakuza Kiwami support is secondary.',
  'renodx.page.hdr.disable-double-tonemapping':
    'If the image looks washed out, disable Auto HDR and RTX HDR to avoid double tonemapping.',
  'renodx.the_first_berserker_khazan.tonemapping':
    'Tonemapping issues remain; testing was limited.',
  'renodx.ue.extended.a.way.out.1': 'This configuration has limited playtesting.',
  'renodx.ue.extended.abiotic.factor.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.assetto.corsa.rally.1': "Enable the game's native HDR.",
  'renodx.ue.extended.astroneer.1': 'Color-grading errors and flickering may still occur.',
  'renodx.ue.extended.bodycam.1': 'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.borderlands.4.1': "Enable the game's native HDR.",
  'renodx.ue.extended.chained.together.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.chained.together.2':
    'RenoDX slider changes do not apply in real time in this game.',
  'renodx.ue.extended.choo.choo.charles.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.chromatic.conundrum.1':
    'Upgrade Path is incompatible with this title and causes broken rendering.',
  'renodx.ue.extended.conan.exiles.enhanced.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.crab.champions.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.dead.as.disco.1': "Enable the game's native HDR.",
  'renodx.ue.extended.deep.rock.galactic.1': "Enable the game's native HDR.",
  'renodx.ue.extended.deep.rock.galactic.rogue.core.2':
    "Keep the game's native HDR disabled; its native HDR path is broken.",
  'renodx.ue.extended.escape.the.backrooms.2': 'This configuration has limited playtesting.',
  'renodx.ue.extended.everwind.1': 'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.far.far.west.1': "Enable the game's native HDR.",
  'renodx.ue.extended.frostpunk.2.1':
    'The RenoDX UI brightness slider controls paper white in this game.',
  'renodx.ue.extended.grounded.2.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.hellblade.ii.senua.s.saga.1': "Enable the game's native HDR.",
  'renodx.ue.extended.hellblade.ii.senua.s.saga.2':
    'RenoDX slider changes do not apply in real time in this game.',
  'renodx.ue.extended.hellblade.ii.senua.s.saga.3': 'This configuration has limited playtesting.',
  'renodx.ue.extended.hi.fi.rush.2':
    'The Engine.ini HDR path overexposes shading; this title uses the compatible Upgrade Path.',
  'renodx.ue.extended.hi.fi.rush.3':
    'Gameplay highlights are clamped to the UI brightness setting.',
  'renodx.ue.extended.inzoi.1': 'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.jusant.1': "Enable the game's native HDR.",
  'renodx.ue.extended.lego.batmantm.legacy.of.the.dark.knight.1': "Enable the game's native HDR.",
  'renodx.ue.extended.lego.batmantm.legacy.of.the.dark.knight.2':
    'RenoDX slider changes do not apply in real time in this game.',
  'renodx.ue.extended.lego.batmantm.legacy.of.the.dark.knight.3':
    'This configuration has limited playtesting.',
  'renodx.ue.extended.lies.of.p.1': "Enable the game's native HDR.",
  'renodx.ue.extended.lies.of.p.2': 'RenoDX slider changes do not apply in real time in this game.',
  'renodx.ue.extended.lies.of.p.3': 'This configuration has limited playtesting.',
  'renodx.ue.extended.little.nightmares.ii.1': 'Color-grading issues remain.',
  'renodx.ue.extended.mafia.the.old.country.1': "Enable the game's native HDR.",
  'renodx.ue.extended.meccha.chameleon.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.mortal.shell.ii.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.motor.town.behind.the.wheel.1':
    'RenoDX slider changes do not apply in real time in this game.',
  'renodx.ue.extended.nobody.wants.to.die.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.quarantine.zone.the.last.check.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.ready.or.not.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.ready.or.not.2':
    'RenoDX slider changes do not apply in real time in this game.',
  'renodx.ue.extended.ready.or.not.3': 'This configuration has limited playtesting.',
  'renodx.ue.extended.rv.there.yet.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.s.t.a.l.k.e.r.2.heart.of.chornobyl.1': "Enable the game's native HDR.",
  'renodx.ue.extended.satisfactory.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.sifu.1': 'Peak brightness remains limited in some content.',
  'renodx.ue.extended.solarpunk.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.star.wars.zero.companytm.1': "Enable the game's native HDR.",
  'renodx.ue.extended.subnautica.2.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.the.blood.of.dawnwalker.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.the.enjenir.the.engineering.physics.building.simulator.1':
    'Add these settings to Engine.ini for the UE Extended HDR path.',
  'renodx.ue.extended.the.idolm.ster.starlit.season.2':
    'Some communication and stage lighting remain clamped or do not produce HDR highlights.',
  'renodx.ue.extended.tokyo.xtreme.racer.1': "Enable the game's native HDR.",
  'renodx.ue.extended.until.dawn.1': "Enable the game's native HDR.",
  'renodx.ue.extended.what.remains.of.edith.finch.1':
    'If HDR is clamped with high-DPI scaling, temporarily set Windows scaling to 100%, launch the game once, then restore the preferred scaling.',
  'renodx.ue_extended.hdr_engine_ini': 'For the UE5 HDR path, add these settings to Engine.ini.',
  'renodx.ue_extended.lut_update':
    'For UE5.3 and newer, add this setting to enable real-time sliders.',
  'renodx.unity.60.parsecs.1': 'Tonemapping and color-grading changes do not appear in real time.',
  'renodx.unity.american.fugitive.2': "Set the game's Graphics Quality to Medium or higher.",
  'renodx.unity.aragami.1': 'Tonemapping and color grading update after restarting the level.',
  'renodx.unity.bendy.and.the.ink.machine.2':
    'Tonemapping and color-grading changes do not appear in real time.',
  'renodx.unity.bionic.bay.1': 'The game is not yet fully playable with this profile.',
  'renodx.unity.biped.1':
    'Load a save point to refresh tonemapping and color grading after changing sliders.',
  'renodx.unity.cloverpit.1': "Launch the game's DirectX 11 option.",
  'renodx.unity.deadcore.redux.demo.2':
    'Tonemapping and color-grading changes do not appear in real time.',
  'renodx.unity.dragon.quest.builders.1':
    'Enable in-game bloom; it can be disabled later in RenoDX.',
  'renodx.unity.dread.templar.1':
    'Applying or saving RenoDX settings crashes the game, but the settings are still saved.',
  'renodx.unity.dreamfall.chapters.the.final.cut.2': 'Save-preview images are broken.',
  'renodx.unity.drova.forsaken.kin.1': 'Use Borderless Windowed mode.',
  'renodx.unity.dungeons.2.2':
    'The main menu is black; rendering returns to normal after loading into the game.',
  'renodx.unity.dungeons.4.1':
    "Change the game's Brightness or Gamma control to refresh the LUT after adjusting RenoDX.",
  'renodx.unity.eastshade.1': "Open the game's Brightness control and save it to refresh the LUT.",
  'renodx.unity.for.the.king.ii.1':
    'Tonemapping and color-grading changes do not appear in real time.',
  'renodx.unity.ghost.of.a.tale.2': 'Enable in-game bloom; it can be disabled later in RenoDX.',
  'renodx.unity.herdling.1': "Disable the game's native HDR in its configuration file.",
  'renodx.unity.hollow.cocoon.2': "Set the game's Rendering Quality to 100%.",
  'renodx.unity.house.flipper.2.2':
    "Change the game's Saturation control to refresh tonemapping and color grading.",
  'renodx.unity.jotunnslayer.hordes.of.hel.2':
    'Tonemapping and color-grading changes do not appear in real time.',
  'renodx.unity.keywe.1': 'Tonemapping and color-grading changes do not appear in real time.',
  'renodx.unity.mouthwashing.1': 'Use Borderless display mode.',
  'renodx.unity.my.friend.pedro.2': 'Restart the level to refresh tonemapping and color grading.',
  'renodx.unity.necropolis.brutal.edition.1':
    'Load ReShade through Ultimate ASI Loader for this 32-bit game.',
  'renodx.unity.oddworld.soulstorm.enhanced.edition.2':
    'Restart a checkpoint or level to refresh tonemapping and color grading.',
  'renodx.unity.order.13.2':
    'Change the in-game Brightness setting to refresh tonemapping and color grading.',
  'renodx.unity.outer.wilds.1': 'Tonemapping and color-grading changes do not appear in real time.',
  'renodx.unity.peak.1': 'Launch the game with DirectX 11.',
  'renodx.unity.prince.of.persia.the.lost.crown.1':
    'RenoDX cannot affect color grading beyond Peak and UI Brightness in this game.',
  'renodx.unity.prince.of.persia.the.lost.crown.2':
    'Use the dedicated Luma Framework mod for full correction.',
  'renodx.unity.reset_display_controls':
    "Keep the game's brightness, contrast, and gamma controls at their default values unless a title note says otherwise.",
  'renodx.unity.road.redemption.1':
    'Tonemapping and color-grading changes do not appear in real time.',
  'renodx.unity.ruined.king.a.league.of.legends.storytm.1': 'The pause-menu background is broken.',
  'renodx.unity.shadows.awakening.1':
    'Tonemapping and color-grading changes do not appear in real time.',
  'renodx.unity.skate.story.2': "Disable the game's native HDR.",
  'renodx.unity.sker.ritual.2':
    "Open the game's graphics settings and select Apply to refresh tonemapping and color grading.",
  'renodx.unity.summoner.s.war.chronicles.1': 'Enable bloom in the game settings.',
  'renodx.unity.tales.of.berseria.remastered.2':
    'The correction also affects animated FMV cutscenes.',
  'renodx.unity.towaga.among.shadows.2': 'Enable post-processing in the game settings.',
  'renodx.unity.trailmakers.1': 'Enable post-processing at any quality level.',
  'renodx.unity.trailmakers.2': 'Enable Internal HDR in the game settings.',
  'renodx.unity.turbo.golf.racing.1': "Enable post-processing in the game's graphics settings.",
  'renodx.unity.ultros.1': 'Enable color grading in the game settings.',
  'renodx.unity.v.rising.1': 'In solo play, toggle the Pause or Options menu to refresh the LUT.',
  'renodx.unity.v.rising.2':
    'In multiplayer, stand in sunlight or open Graphics > Calibrate Brightness and confirm the default value of 50 to refresh the LUT.',
  'renodx.unity.viewfinder.2': 'Enable post-processing in the game settings.',
  'renodx.unity.void.crew.2': 'DLSS clamps colors to BT.709.',
  'renodx.unity.windowed': 'Avoid Exclusive Fullscreen; use Borderless or Windowed mode.',
  'renodx.unity.wizard.with.a.gun.2':
    'Increase the Highlights slider substantially because the default highlights are dim.',
  'renodx.unreal.bright.memory.infinite.2': 'Use DirectX 12.',
  'renodx.unreal.chernobylite.1': 'Use DirectX 12.',
  'renodx.unreal.chernobylite.2':
    "Changing DLSS quality can temporarily disable the game's excessive sharpening, but the workaround must be repeated each session.",
  'renodx.unreal.colony.ship.a.post.earth.role.playing.game.1':
    'Some menus and the loading screen still need fixes.',
  'renodx.unreal.dahlia.view.1':
    "Disable the game's broken native HDR, especially when using DirectX 12.",
  'renodx.unreal.darksiders.3.1': 'Non-boss enemy health bars do not update correctly.',
  'renodx.unreal.darksiders.genesis.1': 'Some loading-screen text can render as solid blocks.',
  'renodx.unreal.deadlink.1': 'Use DirectX 12.',
  'renodx.unreal.dragon.ball.z.kakarot.1': 'Some colors remain inaccurate.',
  'renodx.unreal.en.garde.1': 'DirectX 12 crashes; use DirectX 11.',
  'renodx.unreal.enotria.the.last.song.1':
    'Slider changes apply only after a scene change or after returning from the main menu.',
  'renodx.unreal.everspace.1':
    'Use the 64-bit RSG-Win64-Shipping.exe. This configuration was tested only with the GOG release.',
  'renodx.unreal.everspace.2.1': 'Use DirectX 12.',
  'renodx.unreal.flyknight.filter_warning': 'In-game filters can alter HDR presentation.',
  'renodx.unreal.flyknight.limited_testing': 'This configuration has limited testing.',
  'renodx.unreal.forgive.me.father.1': 'Some text can render as solid blocks.',
  'renodx.unreal.ghostrunner-2.limited_testing': 'Tonemapping issues remain; testing was limited.',
  'renodx.unreal.ghostrunner.2.1': 'Output remains limited to BT.709.',
  'renodx.unreal.granblue.fantasy.versus.1':
    'Character and map highlights are clamped to the UI brightness level.',
  'renodx.unreal.guilty.gear.strive.1':
    'Health bars do not update, character selection can show corruption, and the tension meter is excessively bright.',
  'renodx.unreal.hell.is.us.1': "Disable the game's native HDR.",
  'renodx.unreal.hell.is.us.2': 'This profile was tested only with the demo.',
  'renodx.unreal.industria.1': 'Use DirectX 12.',
  'renodx.unreal.islands.of.insight.1': 'Output remains limited to BT.709.',
  'renodx.unreal.jdm.japanese.drift.master.1':
    'Slider changes require a scene change before they appear.',
  'renodx.unreal.kena.bridge.of.spirits.1':
    'Cutscene brightness is clamped to the UI brightness level.',
  'renodx.unreal.kingdom.hearts.iii.1': 'Texture flickering can occur.',
  'renodx.unreal.lego.2k.drive.1':
    'The mod works without resource upgrades, although some vehicle headlights may still be clamped.',
  'renodx.unreal.lords.of.the.fallen.2023.1': "Disable the game's native HDR.",
  'renodx.unreal.lords.of.the.fallen.2023.2': 'Disable Easy Anti-Cheat before using the mod.',
  'renodx.unreal.lost.soul.aside.1': "Disable the game's native HDR.",
  'renodx.unreal.marvel.s.midnight.suns.1': "Disable the game's native HDR.",
  'renodx.unreal.metal.eden.1': 'The main menu and respawn screen can show corruption.',
  'renodx.unreal.metal.eden.2': 'This profile was tested only with the demo.',
  'renodx.unreal.murky.divers.1': 'Gamut clamping may be required.',
  'renodx.unreal.neverness.to.everness.1': "Follow the game's detailed RenoDX setup instructions.",
  'renodx.unreal.ninja.gaiden.2.black.1': "Disable the game's native HDR.",
  'renodx.unreal.ninja.gaiden.2.black.2':
    'RenoDX slider changes do not apply in real time in this game.',
  'renodx.unreal.palworld.1': 'Disable DLSS because it clamps output to SDR.',
  'renodx.unreal.palworld.limited_testing': 'This configuration has limited testing.',
  'renodx.unreal.police.simulator.patrol.officer.1': "Disable the game's native HDR.",
  'renodx.unreal.reanimal.1':
    'The game already provides a proper custom HDR implementation; RenoDX is generally unnecessary.',
  'renodx.unreal.redout.2.1': 'The game may crash with this profile.',
  'renodx.unreal.returnal.1': "Disable the game's native HDR after every launch.",
  'renodx.unreal.runescape.dragonwilds.1':
    'If the game is unstable, switch to DirectX 11 in its graphics settings.',
  'renodx.unreal.runescape.dragonwilds.2':
    'Slider changes apply only after a scene change or after returning from the main menu.',
  'renodx.unreal.scarlet.nexus.1': 'Visual-novel scenes are broken.',
  'renodx.unreal.six.days.in.fallujah.1':
    'A dark artifact can appear around the sun, and smoke may render too dark.',
  'renodx.unreal.sonic.racing.crossworlds.1': 'Slider changes apply after restarting the track.',
  'renodx.unreal.sonic.racing.crossworlds.2':
    'Bright elements are clamped to UI brightness, and the Water Palace sky remains excessively bright.',
  'renodx.unreal.split.fiction.1': "Disable the game's native HDR.",
  'renodx.unreal.split.fiction.2': 'Slider changes may require a scene change before they appear.',
  'renodx.unreal.stellar.blade.1': "Disable the game's native HDR.",
  'renodx.unreal.stellar.blade.2':
    'On ultrawide displays, use the in-game Auto aspect ratio to avoid NIKKE minigame problems.',
  'renodx.unreal.tales.of.arise.1': 'Bloom can occasionally render incorrectly.',
  'renodx.unreal.tales.of.arise.2':
    'SMAA and SMAA + TAA are unsupported; use TAA or disable anti-aliasing.',
  'renodx.unreal.tales.of.kenzera.zau.1':
    'Update libxess.dll before using XeSS to prevent crashes.',
  'renodx.unreal.tekken.7.1': 'Some stages are clamped to the UI brightness level.',
  'renodx.unreal.the.cabin.factory.1':
    'The mod works without resource upgrades, but color grading is not corrected.',
  'renodx.unreal.the.medium.1': "Disable the game's native HDR.",
  'renodx.unreal.the.medium.2':
    'Highlights in the spirit world are clamped to the UI brightness level.',
  'renodx.unreal.the.outer.worlds.spacer.s.choice.edition.1':
    'This optional upgrade prevents HDR from being disabled in some scenes but breaks FMVs.',
  'renodx.unreal.the.smurfs.dreams.1': 'The RenoDX UI brightness slider also affects FMVs.',
  'renodx.unreal.the.thaumaturge.1': 'Some scenes remain brightness-clamped.',
  'renodx.unreal.tiny.tina.s.wonderlands.1': "Disable the game's FidelityFX Sharpening.",
  'renodx.unreal.vampire.the.masquerade.bloodlines.2.1': 'Cutscenes remain brightness-clamped.',
} as const;
export const RENODX_MESSAGE_CONTEXTS = {
  'renodx.black_myth_wukong.hdr': 'guidance.engine_ini',
  'renodx.external.discord': 'guidance.compatibility',
  'renodx.external.nexus': 'guidance.compatibility',
  'renodx.generic.ue_extended': 'guidance.compatibility',
  'renodx.generic.unity': 'guidance.compatibility',
  'renodx.generic.unreal_legacy': 'guidance.compatibility',
  'renodx.main.assassin.s.creed.iv.black.flagtm.1': 'guidance.compatibility',
  'renodx.main.atelier.yumia.the.alchemist.of.memories.the.envisioned.land.1':
    'guidance.compatibility',
  'renodx.main.atlas.fallen.dx12.1': 'guidance.compatibility',
  'renodx.main.atlas.fallen.dx12.2': 'guidance.warning',
  'renodx.main.clive.barker.s.jericho.1': 'guidance.warning',
  'renodx.main.crimson.desert.1': 'guidance.compatibility',
  'renodx.main.days.gone.1': 'guidance.compatibility',
  'renodx.main.dead.island.riptide.definitive.edition.1': 'guidance.warning',
  'renodx.main.dragon.s.dogma.2.1': 'guidance.warning',
  'renodx.main.forza.horizon.6.1': 'guidance.compatibility',
  'renodx.main.ninja.gaiden.4.1': 'guidance.external_tool',
  'renodx.main.ninja.gaiden.sigma.1': 'guidance.external_tool',
  'renodx.main.ninja.gaiden.sigma.2.1': 'guidance.external_tool',
  'renodx.main.opus.echo.of.starsong.full.bloom.edition.1': 'guidance.game_setting',
  'renodx.main.raidou.remastered.the.mystery.of.the.soulless.army.1': 'guidance.compatibility',
  'renodx.main.s.t.a.l.k.e.r.2.heart.of.chornobyl.1': 'guidance.game_setting',
  'renodx.main.sonic.unleashed.recompiled.1': 'guidance.game_setting',
  'renodx.main.sonic.unleashed.recompiled.2': 'guidance.warning',
  'renodx.main.steelrising.1': 'guidance.warning',
  'renodx.main.the.evil.within.2.1': 'guidance.compatibility',
  'renodx.main.trackmania.1': 'guidance.compatibility',
  'renodx.main.yakuza.kiwami.1.1': 'guidance.compatibility',
  'renodx.page.hdr.disable-double-tonemapping': 'guidance.compatibility',
  'renodx.the_first_berserker_khazan.tonemapping': 'guidance.compatibility',
  'renodx.ue.extended.a.way.out.1': 'guidance.compatibility',
  'renodx.ue.extended.abiotic.factor.1': 'guidance.engine_ini',
  'renodx.ue.extended.assetto.corsa.rally.1': 'guidance.game_setting',
  'renodx.ue.extended.astroneer.1': 'guidance.compatibility',
  'renodx.ue.extended.bodycam.1': 'guidance.engine_ini',
  'renodx.ue.extended.borderlands.4.1': 'guidance.game_setting',
  'renodx.ue.extended.chained.together.1': 'guidance.engine_ini',
  'renodx.ue.extended.chained.together.2': 'guidance.compatibility',
  'renodx.ue.extended.choo.choo.charles.1': 'guidance.engine_ini',
  'renodx.ue.extended.chromatic.conundrum.1': 'guidance.warning',
  'renodx.ue.extended.conan.exiles.enhanced.1': 'guidance.engine_ini',
  'renodx.ue.extended.crab.champions.1': 'guidance.engine_ini',
  'renodx.ue.extended.dead.as.disco.1': 'guidance.game_setting',
  'renodx.ue.extended.deep.rock.galactic.1': 'guidance.game_setting',
  'renodx.ue.extended.deep.rock.galactic.rogue.core.2': 'guidance.game_setting',
  'renodx.ue.extended.escape.the.backrooms.2': 'guidance.compatibility',
  'renodx.ue.extended.everwind.1': 'guidance.engine_ini',
  'renodx.ue.extended.far.far.west.1': 'guidance.game_setting',
  'renodx.ue.extended.frostpunk.2.1': 'guidance.compatibility',
  'renodx.ue.extended.grounded.2.1': 'guidance.engine_ini',
  'renodx.ue.extended.hellblade.ii.senua.s.saga.1': 'guidance.game_setting',
  'renodx.ue.extended.hellblade.ii.senua.s.saga.2': 'guidance.compatibility',
  'renodx.ue.extended.hellblade.ii.senua.s.saga.3': 'guidance.compatibility',
  'renodx.ue.extended.hi.fi.rush.2': 'guidance.compatibility',
  'renodx.ue.extended.hi.fi.rush.3': 'guidance.compatibility',
  'renodx.ue.extended.inzoi.1': 'guidance.engine_ini',
  'renodx.ue.extended.jusant.1': 'guidance.game_setting',
  'renodx.ue.extended.lego.batmantm.legacy.of.the.dark.knight.1': 'guidance.game_setting',
  'renodx.ue.extended.lego.batmantm.legacy.of.the.dark.knight.2': 'guidance.compatibility',
  'renodx.ue.extended.lego.batmantm.legacy.of.the.dark.knight.3': 'guidance.compatibility',
  'renodx.ue.extended.lies.of.p.1': 'guidance.game_setting',
  'renodx.ue.extended.lies.of.p.2': 'guidance.compatibility',
  'renodx.ue.extended.lies.of.p.3': 'guidance.compatibility',
  'renodx.ue.extended.little.nightmares.ii.1': 'guidance.compatibility',
  'renodx.ue.extended.mafia.the.old.country.1': 'guidance.game_setting',
  'renodx.ue.extended.meccha.chameleon.1': 'guidance.engine_ini',
  'renodx.ue.extended.mortal.shell.ii.1': 'guidance.engine_ini',
  'renodx.ue.extended.motor.town.behind.the.wheel.1': 'guidance.compatibility',
  'renodx.ue.extended.nobody.wants.to.die.1': 'guidance.engine_ini',
  'renodx.ue.extended.quarantine.zone.the.last.check.1': 'guidance.engine_ini',
  'renodx.ue.extended.ready.or.not.1': 'guidance.engine_ini',
  'renodx.ue.extended.ready.or.not.2': 'guidance.compatibility',
  'renodx.ue.extended.ready.or.not.3': 'guidance.compatibility',
  'renodx.ue.extended.rv.there.yet.1': 'guidance.engine_ini',
  'renodx.ue.extended.s.t.a.l.k.e.r.2.heart.of.chornobyl.1': 'guidance.game_setting',
  'renodx.ue.extended.satisfactory.1': 'guidance.engine_ini',
  'renodx.ue.extended.sifu.1': 'guidance.compatibility',
  'renodx.ue.extended.solarpunk.1': 'guidance.engine_ini',
  'renodx.ue.extended.star.wars.zero.companytm.1': 'guidance.game_setting',
  'renodx.ue.extended.subnautica.2.1': 'guidance.engine_ini',
  'renodx.ue.extended.the.blood.of.dawnwalker.1': 'guidance.engine_ini',
  'renodx.ue.extended.the.enjenir.the.engineering.physics.building.simulator.1':
    'guidance.engine_ini',
  'renodx.ue.extended.the.idolm.ster.starlit.season.2': 'guidance.compatibility',
  'renodx.ue.extended.tokyo.xtreme.racer.1': 'guidance.game_setting',
  'renodx.ue.extended.until.dawn.1': 'guidance.game_setting',
  'renodx.ue.extended.what.remains.of.edith.finch.1': 'guidance.compatibility',
  'renodx.ue_extended.hdr_engine_ini': 'guidance.engine_ini',
  'renodx.ue_extended.lut_update': 'guidance.engine_ini',
  'renodx.unity.60.parsecs.1': 'guidance.compatibility',
  'renodx.unity.american.fugitive.2': 'guidance.game_setting',
  'renodx.unity.aragami.1': 'guidance.compatibility',
  'renodx.unity.bendy.and.the.ink.machine.2': 'guidance.compatibility',
  'renodx.unity.bionic.bay.1': 'guidance.warning',
  'renodx.unity.biped.1': 'guidance.compatibility',
  'renodx.unity.cloverpit.1': 'guidance.compatibility',
  'renodx.unity.deadcore.redux.demo.2': 'guidance.compatibility',
  'renodx.unity.dragon.quest.builders.1': 'guidance.game_setting',
  'renodx.unity.dread.templar.1': 'guidance.warning',
  'renodx.unity.dreamfall.chapters.the.final.cut.2': 'guidance.compatibility',
  'renodx.unity.drova.forsaken.kin.1': 'guidance.game_setting',
  'renodx.unity.dungeons.2.2': 'guidance.warning',
  'renodx.unity.dungeons.4.1': 'guidance.compatibility',
  'renodx.unity.eastshade.1': 'guidance.compatibility',
  'renodx.unity.for.the.king.ii.1': 'guidance.compatibility',
  'renodx.unity.ghost.of.a.tale.2': 'guidance.game_setting',
  'renodx.unity.herdling.1': 'guidance.game_setting',
  'renodx.unity.hollow.cocoon.2': 'guidance.game_setting',
  'renodx.unity.house.flipper.2.2': 'guidance.compatibility',
  'renodx.unity.jotunnslayer.hordes.of.hel.2': 'guidance.compatibility',
  'renodx.unity.keywe.1': 'guidance.compatibility',
  'renodx.unity.mouthwashing.1': 'guidance.game_setting',
  'renodx.unity.my.friend.pedro.2': 'guidance.compatibility',
  'renodx.unity.necropolis.brutal.edition.1': 'guidance.external_tool',
  'renodx.unity.oddworld.soulstorm.enhanced.edition.2': 'guidance.compatibility',
  'renodx.unity.order.13.2': 'guidance.compatibility',
  'renodx.unity.outer.wilds.1': 'guidance.compatibility',
  'renodx.unity.peak.1': 'guidance.compatibility',
  'renodx.unity.prince.of.persia.the.lost.crown.1': 'guidance.compatibility',
  'renodx.unity.prince.of.persia.the.lost.crown.2': 'guidance.external_tool',
  'renodx.unity.reset_display_controls': 'guidance.game_setting',
  'renodx.unity.road.redemption.1': 'guidance.compatibility',
  'renodx.unity.ruined.king.a.league.of.legends.storytm.1': 'guidance.compatibility',
  'renodx.unity.shadows.awakening.1': 'guidance.compatibility',
  'renodx.unity.skate.story.2': 'guidance.game_setting',
  'renodx.unity.sker.ritual.2': 'guidance.compatibility',
  'renodx.unity.summoner.s.war.chronicles.1': 'guidance.game_setting',
  'renodx.unity.tales.of.berseria.remastered.2': 'guidance.compatibility',
  'renodx.unity.towaga.among.shadows.2': 'guidance.game_setting',
  'renodx.unity.trailmakers.1': 'guidance.game_setting',
  'renodx.unity.trailmakers.2': 'guidance.game_setting',
  'renodx.unity.turbo.golf.racing.1': 'guidance.game_setting',
  'renodx.unity.ultros.1': 'guidance.game_setting',
  'renodx.unity.v.rising.1': 'guidance.compatibility',
  'renodx.unity.v.rising.2': 'guidance.compatibility',
  'renodx.unity.viewfinder.2': 'guidance.game_setting',
  'renodx.unity.void.crew.2': 'guidance.compatibility',
  'renodx.unity.windowed': 'guidance.compatibility',
  'renodx.unity.wizard.with.a.gun.2': 'guidance.compatibility',
  'renodx.unreal.bright.memory.infinite.2': 'guidance.compatibility',
  'renodx.unreal.chernobylite.1': 'guidance.compatibility',
  'renodx.unreal.chernobylite.2': 'guidance.compatibility',
  'renodx.unreal.colony.ship.a.post.earth.role.playing.game.1': 'guidance.compatibility',
  'renodx.unreal.dahlia.view.1': 'guidance.game_setting',
  'renodx.unreal.darksiders.3.1': 'guidance.compatibility',
  'renodx.unreal.darksiders.genesis.1': 'guidance.compatibility',
  'renodx.unreal.deadlink.1': 'guidance.compatibility',
  'renodx.unreal.dragon.ball.z.kakarot.1': 'guidance.compatibility',
  'renodx.unreal.en.garde.1': 'guidance.warning',
  'renodx.unreal.enotria.the.last.song.1': 'guidance.compatibility',
  'renodx.unreal.everspace.1': 'guidance.compatibility',
  'renodx.unreal.everspace.2.1': 'guidance.compatibility',
  'renodx.unreal.flyknight.filter_warning': 'guidance.compatibility',
  'renodx.unreal.flyknight.limited_testing': 'guidance.compatibility',
  'renodx.unreal.forgive.me.father.1': 'guidance.compatibility',
  'renodx.unreal.ghostrunner-2.limited_testing': 'guidance.compatibility',
  'renodx.unreal.ghostrunner.2.1': 'guidance.compatibility',
  'renodx.unreal.granblue.fantasy.versus.1': 'guidance.compatibility',
  'renodx.unreal.guilty.gear.strive.1': 'guidance.warning',
  'renodx.unreal.hell.is.us.1': 'guidance.game_setting',
  'renodx.unreal.hell.is.us.2': 'guidance.compatibility',
  'renodx.unreal.industria.1': 'guidance.compatibility',
  'renodx.unreal.islands.of.insight.1': 'guidance.compatibility',
  'renodx.unreal.jdm.japanese.drift.master.1': 'guidance.compatibility',
  'renodx.unreal.kena.bridge.of.spirits.1': 'guidance.compatibility',
  'renodx.unreal.kingdom.hearts.iii.1': 'guidance.compatibility',
  'renodx.unreal.lego.2k.drive.1': 'guidance.compatibility',
  'renodx.unreal.lords.of.the.fallen.2023.1': 'guidance.game_setting',
  'renodx.unreal.lords.of.the.fallen.2023.2': 'guidance.game_setting',
  'renodx.unreal.lost.soul.aside.1': 'guidance.game_setting',
  'renodx.unreal.marvel.s.midnight.suns.1': 'guidance.game_setting',
  'renodx.unreal.metal.eden.1': 'guidance.compatibility',
  'renodx.unreal.metal.eden.2': 'guidance.compatibility',
  'renodx.unreal.murky.divers.1': 'guidance.compatibility',
  'renodx.unreal.neverness.to.everness.1': 'guidance.external_tool',
  'renodx.unreal.ninja.gaiden.2.black.1': 'guidance.game_setting',
  'renodx.unreal.ninja.gaiden.2.black.2': 'guidance.compatibility',
  'renodx.unreal.palworld.1': 'guidance.game_setting',
  'renodx.unreal.palworld.limited_testing': 'guidance.compatibility',
  'renodx.unreal.police.simulator.patrol.officer.1': 'guidance.game_setting',
  'renodx.unreal.reanimal.1': 'guidance.compatibility',
  'renodx.unreal.redout.2.1': 'guidance.warning',
  'renodx.unreal.returnal.1': 'guidance.game_setting',
  'renodx.unreal.runescape.dragonwilds.1': 'guidance.compatibility',
  'renodx.unreal.runescape.dragonwilds.2': 'guidance.compatibility',
  'renodx.unreal.scarlet.nexus.1': 'guidance.warning',
  'renodx.unreal.six.days.in.fallujah.1': 'guidance.compatibility',
  'renodx.unreal.sonic.racing.crossworlds.1': 'guidance.compatibility',
  'renodx.unreal.sonic.racing.crossworlds.2': 'guidance.compatibility',
  'renodx.unreal.split.fiction.1': 'guidance.game_setting',
  'renodx.unreal.split.fiction.2': 'guidance.compatibility',
  'renodx.unreal.stellar.blade.1': 'guidance.game_setting',
  'renodx.unreal.stellar.blade.2': 'guidance.game_setting',
  'renodx.unreal.tales.of.arise.1': 'guidance.compatibility',
  'renodx.unreal.tales.of.arise.2': 'guidance.game_setting',
  'renodx.unreal.tales.of.kenzera.zau.1': 'guidance.warning',
  'renodx.unreal.tekken.7.1': 'guidance.compatibility',
  'renodx.unreal.the.cabin.factory.1': 'guidance.compatibility',
  'renodx.unreal.the.medium.1': 'guidance.game_setting',
  'renodx.unreal.the.medium.2': 'guidance.compatibility',
  'renodx.unreal.the.outer.worlds.spacer.s.choice.edition.1': 'guidance.compatibility',
  'renodx.unreal.the.smurfs.dreams.1': 'guidance.compatibility',
  'renodx.unreal.the.thaumaturge.1': 'guidance.compatibility',
  'renodx.unreal.tiny.tina.s.wonderlands.1': 'guidance.game_setting',
  'renodx.unreal.vampire.the.masquerade.bloodlines.2.1': 'guidance.compatibility',
} as const;

export type RenoDxSourceCatalog = typeof RENODX_SOURCE_CATALOG;
export type RenoDxMessageKey = keyof RenoDxSourceCatalog;
export type RenoDxMessageContext = (typeof RENODX_MESSAGE_CONTEXTS)[RenoDxMessageKey];
export type RenoDxTranslations = Readonly<Record<RenoDxMessageKey, string>>;
